API doc updates
IBM-Swift/Kitura-Cache pull request #27
Opened 2017-12-01 15:40 UTC by alexwishart

Part of work for this [issue](https://github.ibm.com/arf/planning-swift-solutions/issues/493).

2017-12-04 13:29 UTC, helenmasters commented
Alex, as I can't add myself as a reviewer I'll put some comments here.

- I think it'd be useful to keep the basic sample usage in the README.md to minimise the number of clicks that I would need to perform as a user before finding the information I was looking for.

- In the Statistics struct I would like to see more clarity on the descriptions for hits, misses and numberOfKeys, something more like -

hits - The total number of times an access attempt successfully retrieved an item from the cache.
misses - The total number of times an access attempt did not find an item in the cache.
numberOfKeys - The number of entries currently in the cache. (I realise that this is called numberOfKeys but that is not what a user would be thinking about when using this I don't think...).

- Personally I don't like the description "The statistics of the cache." but something like "Statistics about the cache, including the number of hits and misses and the number of items in the cache." is maybe too wordy? I'm not sure please can you take another look at this.

2017-12-04 13:36 UTC, helenmasters commented
In the top level description the KituraCache class description I think the 'object with a Hashable key' needs some work (and the Hashable needs to be in quotes) as it's not clear if the key needs to be part of the object or not. The second sentence "Time To Live can be specified per entry, or will take a default value specified when the cache is initialised." I found confusing, maybe something like the following would be clearer

"The Time to live (TTL), i.e. the lifespan of the data, can be specified either when the cache is initialised or when an object is added."

2017-12-04 13:48 UTC, helenmasters commented
On the init method the description for the defaultTTL parameter doesn't make sense to me.

"The default Time to Live value (in seconds). Used for cache entries for which the TTL is not specified otherwise. If it is not specified here, the default value is 0 which maps to infinity."

I think that the second two sentences need work - we certainly don't need to talk about infinity! Something like "...the default TTL value is 0 which means that objects in the cache will not expire." might help.

2017-12-04 17:02 UTC, alexwishart commented
@helenmasters Have made the requested changes, plus a few others that I managed to find this afternoon. Have also added new badges and logo to the README - what do you think? 🙂

2017-12-05 05:25 UTC, rolivieri commented
Just added @helenmasters as the reviewer.

2017-12-06 12:51 UTC, helenmasters requested changes

2017-12-06 12:51 UTC, helenmasters commented on README.md
> +//Object with key of 1 retrieved from cache.
It might be clearer to indent both the comment and ... which are within the else { }

2017-12-06 12:51 UTC, helenmasters commented on README.md
> +...
Same comment as above regarding indentation.

2017-12-06 12:51 UTC, helenmasters commented on README.md
> +_Refer to [KituraCache](https://ibm-swift.github.io/Kitura-Cache/Classes/KituraCache) and [Statistics](https://ibm-swift.github.io/Kitura-Cache/Structs/Statistics) for more information and further co
I don't think the words "and further configuration" add anything useful to this sentence - please can you remove them.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/Statistics.swift
> +    /** The total number of entries curently in the cache.
curently - spelling needs fixing to currently!

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/Statistics.swift
> +     ### Usage Example: ###
This is displaying as "The total number of entries curently in the cache. ### Usage Example: ###" when it's loaded so needs fixing.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/Statistics.swift
> +    /** The total number of times an access attempt was unable to retrieve an entry in the cache.
I think "from the cache" would be better than "in the cache" here.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/KituraCache.swift
> +     In this example, item is an instance of a struct object with an id field which conforms to Hashable.
struct and Hashable should be quoted.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/KituraCache.swift
> +     In this example, item has been stored in the cache with an integer key
Full stop at end.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/KituraCache.swift
> +     In this example, objects have been stored in the cache with an integer key
Full stop at end.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/KituraCache.swift
> +     In this example, objects have been stored in the cache with an integer key
Full stop at end.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/KituraCache.swift
> +     In this example, objects have been stored in the cache with an integer key
Full stop at end.

2017-12-06 12:51 UTC, helenmasters commented on Sources/KituraCache/KituraCache.swift
> +     In this example, objects have been stored in the cache with an integer key
Full stop at end.

2017-12-06 14:05 UTC, alexwishart commented
@helenmasters have made tehrequested fixes 🙂

2017-12-07 10:46 UTC, helenmasters commented on Sources/KituraCache/Statistics.swift
> +     let numMisses = cache.statistics.numberOfKeys
This line looks like it was updated in error?

2017-12-07 10:55 UTC, helenmasters commented on Sources/KituraCache/Statistics.swift
> +     The total number of times an access attempt was unable to retrieve an entry in the cache.
Please can you change "in the cache" to "from the cache"

2017-12-07 10:55 UTC, helenmasters commented on Sources/KituraCache/Statistics.swift
> +     The total number of times an access attempt successfully retrieved an entry in the cache.
Please can you change "in the cache" to "from the cache"

2017-12-07 10:58 UTC, helenmasters commented on Sources/KituraCache/KituraCache.swift
> +     - Parameter defaultTTL: The Time to Live value (in seconds) of an entry if a TTL value is not specified when the entry is later added. If the default TTL is not defined during this initialisatio
the entry is later added -> "an entry is added later" I think would be clearer.

2017-12-07 14:54 UTC, helenmasters approved these changes
The changes all look good to me.  
@rolivieri can you do a technical review please, then if you're happy we'll be good to go.

Also @rolivieri do you think us linking to an icon in the Kitura central repository for the README banner headers will cause us issues (rather than having a copy in each local repo)?

2018-01-12 14:29 UTC, helenmasters commented
@tunniclm I can't add you as a reviewer, so tagging you instead 🙂, please can you do a technical review so that this can be merged.

2018-01-16 15:59 UTC, tunniclm approved these changes

2018-01-29 13:14 UTC, merged